# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nmilan <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/07/23 14:20:37 by nmilan            #+#    #+#              #
#    Updated: 2022/07/23 16:12:55 by nmilan           ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

NAME = rush-02

PROG = main.c

all : rush_02

clean :
	rm -f $(NAME)

fclean : clean

rush_02 : 
	gcc -Wall -Wextra -Werror -o $(NAME) $(PROG)


